### ISSUE TITLE
Import Library Projects

### ISSUE THREAD

**Issue by luisreyes** [GetVideostream/cordova-chromecast#56]
This might be a dumb question or request but could you explain how to import the library projects. I don't think the node build process imported them and I need to do it manually.

`adt-bundle\sdk\extras\google\google_play_services\libproject\google-play-services_lib`
`adt-bundle\sdk\extras\android\support\v7\appcompat`
`adt-bundle\sdk\extras\android\support\v7\mediarouter`

**Comment by luisreyes** [comment]
Never mind I fixed the issue.

**Comment by taboca** [comment]
Yet this is a major problem nowadays, which forked projects got it fixed https://github.com/videostream/cordova-chromecast/pull/59
