### ISSUE TITLE
Code example?

### ISSUE THREAD

**Issue by JudeOsborn** [GetVideostream/cordova-chromecast#8]
Would you happen to have a code example where chromecast is working? When I try chrome.cast.initialize() I get the error callback with "api_not_initialized". I've followed the initialization code in tests.js (which is basically the Chrome API). For example, I tried putting this in the bindEvents function:

```
        document.addEventListener('click', function() {
            var applicationID = 'CC1AD845';

            var sessionRequest = new chrome.cast.SessionRequest(applicationID);

            var apiConfig = new chrome.cast.ApiConfig(sessionRequest, function(session) {
                console.log('sessionCallback');
            }, function(available) {
                console.log('receiverCallback');
            });

            chrome.cast.initialize(apiConfig, function() {
                console.log('initialize done');
            }, function(err) {
                console.log('initialize error', err);
            });
        });
```

This results in "initialize error' in the console when touching the app. I do have a working Chromecast running on the same network as the phone to which the cordova app is deployed, and the phone can connect using other apps like YouTube, but not a deployed cordova app with this extension. Maybe I'm integrating it wrong somehow. A working code example would be awesome.

**Comment by FuningXu1** [comment]
Are you guys running on emulator or the real devices?
